[env]
_.path = ["~/.local/share/bob/nvim-bin"]

[tools]
"cargo:bob-nvim" = "latest"
ripgrep = "latest"
tree-sitter = "latest"
'npm:vscode-langservers-extracted' = 'latest'
'npm:typescript' = 'latest'
'npm:typescript-language-server' = 'latest'
lua-language-server = "latest"
stylua = 'latest'
'ubi:Kampfkarren/selene' = 'latest'
'npm:@olrtg/emmet-language-server' = 'latest'
'npm:@tailwindcss/language-server' = 'latest'
'npm:@astrojs/language-server' = 'latest'
taplo = 'latest'
'pipx:basedpyright' = 'latest'
ruff = 'latest'

[settings.npm]
bun = true
