[env]
_.fnox-env.tools = true

[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[tools]
fnox = "latest"
sops = "latest"
age = "latest"
slsa-verifier = "latest"
cosign = "latest"
cargo-binstall = "latest"
lazygit = "latest"
zoxide = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
usage = "latest"
watchexec = "latest"
gh = "latest"
uv = "latest"
bun = "latest"
node = "latest"
rust = "latest"
eza = "latest"
carapace = "latest"
bat-extras = "latest"
"cargo:topgrade" = "latest"
"go:go.senan.xyz/cliphist" = "latest"
"github:jorgerojas26/lazysql" = "latest"
"github:air-verse/air" = "latest"

[settings]
npm.bun = true
experimental = true
lockfile = true
