[tools]
sops = "latest"
age = "latest"
slsa-verifier = "latest"
cosign = "latest"
cargo-binstall = "latest"
lazygit = "latest"
zoxide = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
usage = "latest"
watchexec = "latest"
gh = "latest"
uv = "latest"
bun = "latest"
node = "latest"
rust = "latest"
eza = "latest"
carapace = "latest"
bat-extras = "latest"
"cargo:topgrade" = "latest"
"go:go.senan.xyz/cliphist" = "latest"

[settings]
npm.bun = true
experimental = true
lockfile = true
