[tools]
chezmoi = "latest"
cargo-binstall = "latest"
bun = "latest"
uv = "latest"
lazygit = "latest"
zoxide = "latest"
node = "latest"
pnpm = "latest"
github-cli = "latest"
bat = "latest"
zig = "latest"
fzf = "latest"
fd = "latest"
rust = "latest"
usage = "latest"
go = "latest"

[settings]
npm.bun = true
experimental = true
